name: CI
on: [push]
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install wabt
      - uses: actions/setup-go@v2
        with:
          go-version: '1.18.x'
      - uses: jwlawson/actions-setup-cmake@v1.12
        with:
          cmake-version: '3.16.x'
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Make go deps
        run: make deps
      - name: Build Rosetta
        run: make
      - name: Clone flow-go
        run: python3 setup.py
      - name: Build flow-go relic and other tools
        working-directory: ./flow-go
        run: make install-tools
      - name: Install Flow Client In Docker
        run: cd flow-go/integration/localnet && sh client/client.sh
      - name: Set up Localnet
        run: bash -c 'cd flow-go/integration/localnet/ && make -e OBSERVER=2 init && make start'
      - name: Ensure Observer is started
        run: docker ps -f name=localnet_observer_1_1 | grep localnet_observer
      - name: Get Client Version ensuring the client is provisioned
        run: docker run --network host localnet-client /go/flow -f /go/flow-localnet.json -n observer version
      - name: Wait for a default waiting period until a clean state
        run: sleep 10
      - name: Get Status ensuring the access endpoint is online
        run: docker run --network host localnet-client /go/flow -f /go/flow-localnet.json -n access status